spring.application.name=utensils

logging.level.org.mongodb.driver.cluster=DEBUG
logging.level.org.mongodb.driver.connection=DEBUG
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}




spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${DATASOURCE_DRIVER}


# Hibernate/JPA Settings (This automatically creates the SQL tables for you!)
spring.jpa.hibernate.ddl-auto=${HIBERNATE_AUTO}





# Email SMTP Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
# Paste your 16-letter App Password below (No spaces)
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_KEY}
frontend.url=${FRONTEND_URL}
python.url=${PYTHON_URL}
