spring.application.name=utensils

logging.level.org.mongodb.driver.cluster=DEBUG
logging.level.org.mongodb.driver.connection=DEBUG
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}




spring.datasource.url=jdbc:mysql://mysql-19a6f146-utensilpro-3.d.aivencloud.com:16864/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Hibernate/JPA Settings (This automatically creates the SQL tables for you!)
spring.jpa.hibernate.ddl-auto=update





# Email SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
# Paste your 16-letter App Password below (No spaces)
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_KEY}
frontend.url=${FRONTEND_URL}
python.url=${PYTHON_URL}
